# Site info
title: Ian Perrin
tagline: Dad, technologist, biker and SWFC fan.
description: Dad, technologist, home automation enthusiast, biker and SWFC fan.
author: ianperrin
lang: en_GB
repository: ianperrin/ianperrin.github.io

# Outputting
baseurl: ""
timezone: Europe/London

# Generator exclusions
exclude:
  - vendor
  - /LICENSE
  - /params.json
  - /README.md

# Site config
highlighter: rouge

sass:
  style: compressed

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Collections
collections_dir: _collections
collections:
  bwr-trips:
    title: The Beautiful Way Round
    permalink: /the-beautiful-way-round/#bwr-:name

# Front Matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
