# Site settings
name: Ian Perrin
description: Dad, technologist, home automation enthusiast, biker and SWFC fan.
author: Ian Perrin
url: https://ianperrin.com
lang: en_GB

# Handling Reading
encoding:     "utf-8"

# Outputting
timezone:      "Europe/London"
permalink:     "/:categories/:title"

# Gems
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "minimal"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "minimal"
      author: "Ian Perrin"
