# Site info
title: Ian Perrin
tagline: Dad, technologist, biker and SWFC fan.
description: Dad, technologist, home automation enthusiast, biker and SWFC fan.
author: ian_perrin
lang: en_GB
repository: ianperrin/ianperrin.github.io

# SEO
twitter:
  username: ian_perrin
  card: summary

# Outputting
baseurl: ""
timezone: Europe/London

# Generator exclusions
exclude:
  - vendor
  - /LICENSE
  - /Gemfile
  - /Gemfile.lock
  - /params.json
  - /README.md

# Site config
highlighter: rouge

# Sass/SCSS
sass:
  style: compressed

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Collections
collections_dir: _collections
collections:
  bwr-trips:
    title: The Beautiful Way Round
    description: A motorcycle tour of the English and Welsh coastline.
    icon: fa-route
    permalink: /the-beautiful-way-round/#bwr-:name

# Front Matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
