# Site settings
name: Ian Perrin
description:
author: Ian Perrin
url: http://ianperrin.com

# Handling Reading
encoding:     "utf-8"

# Outputting
timezone:      "Europe/London"
permalink:     "/:categories/:title"

# Gems
gems:
  - jekyll-sitemap
  - jekyll-feed

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Ian Perrin"
